# Generated by Django 5.1.6 on 2025-04-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_initial'),
        ('projects', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='axis',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(default='', upload_to='processed/'),
        ),
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
