# Generated by Django 5.1.6 on 2025-04-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_image_axis_image_category_image_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.BooleanField(),
        ),
    ]
