# Generated by Django 5.1.6 on 2025-05-14 10:25

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_alter_image_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(default='', storage=storages.backends.s3.S3Storage(), upload_to='processed/'),
        ),
    ]
