# Generated by Django 5.1.6 on 2025-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0005_alter_image_image_alter_image_processed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
