# Generated by Django 5.1.6 on 2025-05-14 10:25

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blueprint_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='uploads/blueprints/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(),
        ),
    ]
